# Generated by Django 4.0.3 on 2022-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('cancel', 'Cancelled'), ('complete', 'Completed'), ('open', 'Open'), ('in_progress', 'In Progress')], default='open', max_length=100),
        ),
    ]
